config/routes.rb
Rails.application.routes.draw do
  devise_for :artists
  devise_for :users
  root to: "pages#home"
  resources :search, only: :index
  resources :shortlists
  resources :artists do
    resources :shortlisted_artists, only: :create
    resources :artworks, only: :destroy
  end
  resources :shortlisted_artists
  resources :users
  resources :artworks, except: :show
  resources :opportunities do
    resources :applications, only: %i[destroy toggle_success new create]
  end
  resources :applications, except: :edit do
    member do
      patch :toggle_success
    end
  end

  get "/my-opportunities", to: "opportunities#mine"
end

app/models/artist.rb
class Artist < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :artist_tags, dependent: :destroy
  has_many :tags, through: :artist_tags
  has_many :artworks, dependent: :destroy
  has_many :applications, dependent: :destroy
  has_many :opportunities, through: :applications

  has_one_attached :photo
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show index]

  skip_before_action :authenticate_artist!, only: %i[show index]

  before_action :set_artist, only: %i[show update edit destroy]

  def index
    if params[:query].present?
      tagsquery = params[:query].split
      @artists = Artist.joins(:tags).where(tags: {name: tagsquery} ).uniq
    else
      @artists = Artist.all
    end
  end

  def show
    @artworks = @artist.artworks
    @shortlisted_artist = ShortlistedArtist.new
    @shortlist = Shortlist.find_by(user: current_user)
    @tags = @artist.tags
    @applications = @artist.applications
    @artist_opportunities = @artist.opportunities
    @new_artwork = Artwork.new
    if params[:tags]
      @new_tags = params[:tags].split(", ")
      @new_tags.each do |tag|
        tag_create = Tag.find_or_create_by(name: tag)
        if current_artist.tags.include?(tag_create) == false
          ArtistTag.create(tag: tag_create, artist: current_artist)
        end
        # end
      end
    end
  end

  def edit
  end

  def update
    @artist.update(artist_params)
    redirect_to current_user
  end

  def destroy
    @artist.destroy
    redirect_to new_artist_registration
  end

  private

  def artist_params
    params.require(:artist).permit(:location, :first_name, :last_name, :tags, :bio, :photo)
  end

  def set_artist
    @artist = Artist.find(params[:id])
  end

end

app/views/artists/_form.html.erb
<%= simple_form_for(@artist) do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :location %>
  <%= f.input :pronouns %>
  <%= f.input :bio %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/artists/_modal_carousel.html.erb
<!-- Button trigger modal -->
<button type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-width">
    <div class="modal-content bg-dark text-light">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel"><%= "#{@artist.first_name} ##{artwork.name}" %></h1>
        <%#= "#{artist.last.first_name}" %>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">

        <!-- Carousel -->
        <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner modal-carousel-height">
            <div class="carousel-item active" data-bs-interval="3000">
              <img src="https://source.unsplash.com/random/300x300" class="d-block carousel-img" alt="...">
            </div>
            <div class="carousel-item" data-bs-interval="3000">
              <img src="https://source.unsplash.com/random/300x300" class="d-block carousel-img" alt="...">
            </div>
            <div class="carousel-item" data-bs-interval="3000">
              <img src="https://source.unsplash.com/random/300x300" class="d-block carousel-img" alt="...">
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>

        </div>

      </div>
      <div class="modal-footer">
        <%#= render partial: "shared/tags_container", locals: { tags: artist.tags } %>
      </div>
    </div>
  </div>
</div>

app/views/artists/edit.html.erb
<div class="container">
  <h1>Hi <%= @artist.first_name %></h1>
  <p>Edit your profile</p>

  <%= render "form", artist: @artist %>

  <p>Thinking of leaving us?<p>
  <% if @artist == current_artist %>
        <%= link_to "delete account", artist_path, class: "btn btn-danger" %>
  <% end %>
</div>

app/views/artists/index.html.erb
<div class="page-wrapper">
<div class="container my-3 artist-card__container">
<%# <%= form_with url: artists_path, method: :get, class: "d-flex" do %>
  <%#= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find an artist"
  %>
  <%#= submit_tag "Search", class: "btn btn-primary" %>
<%# end %>

<h1>All Artists</h1>
  <% @artists.each do |artist| %>
    <%= link_to artist_path(artist.id), class: "text-decoration-none artist-card__link" do %>
      <%= render partial: "shared/artist_card", locals: {artist: artist} %>
    <% end %>
  <% end %>
</div>

    <%= link_to artworks_path(query: params[:query]), class: "text-decoration-none" do %>
    <div class="tab-button tab-button--artworks">
      <div class="sideways-text">Artworks</div>
    </div>
  <% end %>

  <%= link_to opportunities_path(query: params[:query]), class: "text-decoration-none" do %>
    <div class="tab-button tab-button--opportunities">
      <div class="sideways-text">Opportunities</div>
    </div>
  <% end %>
</div>

app/views/artists/show.html.erb
<div class="grid-artist-show">
  <aside class="d-flex justify-content-end">
    <div class="side">
      <%# TODO: change below link path %>
      <%= link_to :back, class: "text-decoration-none" do %>
        <div class="d-flex align-items-center">
          <i class="fa-solid fa-circle-arrow-left fs-2"></i>
        <% end %>
          <p class="mb-0 ms-2">back</p>
        </div>
      <%#= link_to "< back to results", :back %>

      <div class="artist-avatar animate__animated animate__fadeIn animate__delay-1s" style="background-image: url('<%= image_path (@artist.profile_image) %>'); width: 300px;">
      </div>
      <h2>
        <%= "#{@artist.first_name} #{@artist.last_name}" %>
      </h2>
      <p>
        <%= icon('fa-solid', 'user')%> <%= @artist.pronouns %>
      </p>
      <p>
        <%= icon('fa-solid', 'location-dot')%> <%= @artist.location ? @artist.location : "" %>
      </p>

      <%= render partial: "shared/tags_container", locals: { tags: @artist.tags } %>

    <div class="tags-holder">
      <% if current_artist == @artist %>
        <form action='/artists/<%= @artist.id %>' data-controller="tom-select">
          <div class="d-flex flex-row w-100">
            <input type="hidden" value="" name="tags" id="tag-box">
            <select data-tom-select-target="selector" data-action="input->tom-select#change" multiple name="newtag" id="select-tags" class="p-0 flex-grow-1">
              <% Tag.all.each do |tag| %>
                <option value='<%= tag.name %>'><%= tag.name %></option>
              <% end %>
            </select>
          <input type="submit" value="Add Tags" class="btn btn-primary btn-sm">
          </div>
        </form>
      <% end %>

    </div>

      <p>
        <%= @artist.bio %>
      </p>

      <% if current_user %>

        <%= simple_form_for [@artist, @shortlisted_artist] do |f| %>
          <%= f.submit "+ Favourite", class: "btn btn-primary" %>
        <% end %>

      <% end %>


  </aside>

  <main>
    <%# <h2>Works</h2> %>
    <% if current_artist == @artist %>
    <div class="add_top_div d-flex justify-content-start align-items-center mb-4">
      <button type="button" class="circle" data-bs-toggle="modal" data-bs-target="#exampleModal">
        <div class="circle::before"></div>
        <div class="plus-side"></div>
      </button>
      <div class="add_top_div mb-0 ms-2" id="show"><h6>Add artwork</h6></div>
    </div>
    <% end %>
    <div class="artwork-container">

      <% @artworks.each do |artwork| %>
        <%= render partial: "shared/artwork", locals: { artwork: artwork } %>
      <% end %>

      <% if @artist == current_artist %>
        <%= render "shared/add_artwork_modal", locals: { new_artwork: @new_artwork } %>
      <% end %>

      <%# THIS IS A TEST RENDER JUST TO SEE HOW IT LOOKS... delete later %>
      <%#= render partial: "shared/artwork" %>
    </div>
  </main>
</div>
<%# <%= raise %>