config/routes.rb
Rails.application.routes.draw do
  devise_for :artists
  devise_for :users
  root to: "pages#home"
  resources :search, only: :index
  resources :shortlists
  resources :artists do
    resources :shortlisted_artists, only: :create
    resources :artworks, only: :destroy
  end
  resources :shortlisted_artists
  resources :users
  resources :artworks, except: :show
  resources :opportunities do
    resources :applications, only: %i[destroy toggle_success new create]
  end
  resources :applications, except: :edit do
    member do
      patch :toggle_success
    end
  end

  get "/my-opportunities", to: "opportunities#mine"
end

app/views/shared/_add_artwork_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog m">
    <div class="modal-content">
      <div class="modal-content bg-dark text-light">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Artwork</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">

        <div data-controller="toms-no2">
        <%= simple_form_for(@new_artwork) do |f| %>
        <%= f.input :name %>
        <%= f.input :genre %>

        <label class="form-label string optional" for="tags">Tags</label>
          <input type="hidden" value="" name="tags" id="worktag-box">
            <select data-toms-no2-target="artwork" data-action="input->toms-no2#tagger" multiple name="newtags" id="select-tags" class="p-0 flex-grow-1">
              <% Tag.all.each do |tag| %>
                <option value='<%= tag.name %>'><%= tag.name %></option>
              <% end %>
            </select>

        <%= f.input :photo, as: :file %>
        <%= f.submit value: "Add", class:"art-add" %>
        <% end %>
        </div>

        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_application_card.html.erb
<div class="application-card">
  <div class="application-card__info">
    <div class="d-flex justify-content-between">
      <h4>
        <%= link_to application.opportunity.title, opportunity_path(application.opportunity), class: "text-decoration-none" %>
      </h4>
        <% if application.success %>
          <span class="text-success fw-bold">Accepted!</span>
        <% else %>
          <span class="text-warning fw-bold">Pending</span>
        <% end %>
    </div>
        <p>
          <strong>Curated by: </strong>
          <%= "#{application.opportunity.user.first_name} #{application.opportunity.user.last_name}" %>
        </p>
    <div class="application-card__inner">
      <div>
        <p><strong>Location: </strong><%= application.opportunity.location %></p>
        <p><strong>Date: </strong><%= application.opportunity.date ? application.opportunity.date.strftime("%d %B, %Y") : "No Date Set" %></p>
      </div>

      <div>
        <p class="fw-bold"><%= "#{application.artist.first_name} #{application.artist.last_name}" %> wrote:</p>
        <p>
          <%= application.content %>
        </p>
      </div>
    </div>

  </div>
</div>

app/views/shared/_artist_card.html.erb
<div class="artist-card">
<div class="artist-card__image" style="background-image: url('<%= artist.artworks.empty? ? "" : artist.artworks.sample.image_url %>')"></div>
    <div class="artist-card__info">
      <h3>
        <%= "#{artist.first_name} #{artist.last_name}" %>
      </h3>
      <p>
        <%= icon('fa-solid', 'location-dot')%>  <%= artist.location ? artist.location : "" %>
      </p>
      <p>
        <%= icon('fa-solid', 'user')%>  <%= artist.pronouns ? artist.pronouns : "" %>
      </p>
      <p class="flex-grow-1">
        <%= artist.bio %>
      </p>

      <%= render partial: "shared/tags_container", locals: { tags: artist.tags } %>
    </div>
</div>

app/views/shared/_artwork.html.erb
<!-- Button trigger modal -->
<button type="button" class="border border-0" data-bs-toggle="modal" data-bs-target="#exampleModal<%= artwork.id %>">
<% artist = artwork.artist %>
  <div class="artwork__card">
    <div class="artwork__frame">
      <% if artwork.photo.key %>
        <%= cl_image_tag artwork.photo.key, class: "img-size" %>
      <% elsif artwork.image_url %>
        <%= image_tag artwork.image_url %>
      <% else %>
         <h2>NAUGHT</h2>
      <% end %>
      <%# leaving this here for when we have cloudinary %>
      <%#= image_tag artwork.image.key %>
    </div>
    <p class="artwork__title"><%= artwork.name %></p>
    <p><%= artwork.genre %></p>
  </div>

  <%# https://www.nationalgalleries.org/sites/default/files/styles/ngs-default/public/externals/40984.jpg?itok=faemvZEs %>

</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal<%= artwork.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-width">
    <div class="modal-content bg-dark text-light">

      <div class="modal-header d-flex justify-content-between">
        <h1 class="modal-title ms-0 fs-5" id="exampleModalLabel"><%= "#{artwork.artist.first_name} #{artwork.artist.last_name}" %></h1>
        <p class="modal-title fs-5"> <%= "#{artwork.name}" %> </p>
        <%# <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> %>

      </div>

      <div class="modal-body d-flex justify-content-center w-100 artwork-modal">

        <% if artwork.photo.key %>
          <%= cl_image_tag artwork.image_url, class: "img-fluid" %>
        <% elsif artwork.image_url %>
          <%= image_tag artwork.image_url %>
        <% else %>
          <h2>NAUGHT</h2>
        <% end %>

      </div>
      <div class="modal-footer d-flex justify-content-between">
        <% if artwork.artist == current_artist %>
          <%= link_to artwork_path(artwork), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'modal-link' do %>
            <i class="fa-regular fa-trash-can fs-5 text-light"></i>
          <% end %>
        <% end %>
        <%# <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button> %>
        <%= render partial: "shared/tags_container", locals: { tags: artwork.tags } %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_artwork_result.html.erb
<div class="artwork__card">
  <div class="artwork__frame">
    <% if artwork.photo.key %>
      <%= image_tag "blobload.gif", class: "lazy", data: {src: cl_image_path(artwork.photo.key), lazy_loader_target: "image" } %>
    <% elsif artwork.image_url %>
      <%= image_tag "blobload.gif", class: "lazy", data: {src: artwork.image_url, lazy_loader_target: "image" } %>
    <% else %>
      <div class="w-100" height="200px">nothing here yet</div>
    <% end %>
  </div>
  <p class="artwork__title"><%= artwork.name %></p>
  <p><%= "#{artwork.artist.first_name} #{artwork.artist.last_name}" %></p>
  <%= render partial: "shared/tags_container", locals: {tags: artwork.tags} %>
</div>

app/views/shared/_edit_shortlist_modal.erb
<%# <button class="shortlist-add" data-bs-toggle="modal" data-bs-target="#exampleModal">
    edit
  </button>

  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Edit Shortlist</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">

          <%= simple_form_for(shortlist) do |f| %>
          <%# <%= f.input :name %>
          <%# <%= f.submit "Update", data: {turbo_method: :update} %>
          <%# <% end %>

        <%# </div>
      </div>
    </div>
  </div> %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_login_modal.html.erb
<button type="button" data-bs-toggle="modal" data-bs-target="#exampleModal" class="nav-link sign-button">
    Login
  </button>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Login</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-footer">
          <%= link_to "I'm an artist", new_artist_session_path, class: "btn btn-primary" %>
          <%= link_to "I'm looking for art", new_user_session_path, class:"btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-aoy sticky-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      All of You
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

      <%= form_with url: search_index_path, method: :get, class: "d-flex navbar-search" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find an artist"
        %>
        <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">



      <!-- Scenario for the user -->

      <% if current_user %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%# <% if current_user.shortlists.empty? %>
            <%# <%= link_to "My Favourites", shortlists_path, class: "nav-link" %>
          <%# <% else %>

            <%= link_to "My Favorites", shortlist_path(current_user.shortlist), class: "nav-link" %>

          <%# <% end %>
        </li>
        <li class="nav-item">
          <%= link_to "My Opportunities", my_opportunities_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://news.artnet.com/app/news-upload/2022/05/SHGH2-e1652097979660-256x256.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <% if current_user %>
              <%= link_to "My Profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "My Account", edit_user_path(current_user), class: "dropdown-item" %>
            <% end %>
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>

      <!-- Scenario for the artist-->

      <% if current_artist %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Applications", applications_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://news.artnet.com/app/news-upload/2022/05/SHGH2-e1652097979660-256x256.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <% if current_artist %>
              <%= link_to "My Profile", artist_path(current_artist), class: "dropdown-item" %>
              <%= link_to "My Account", edit_artist_registration_path(current_artist), class: "dropdown-item" %>
            <% end %>
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>


        <% unless user_signed_in? || artist_signed_in? %>
          <li class="nav-item">
            <%= render "shared/login_modal" %>
          </li>
          <li>
           <%= render "shared/signup_modal" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_opportunity_card.html.erb
<div class="opportunity-card">
<div class="opportunity-card__image">
  <img class="opportunity-card__image" src="<%= image_path (opportunity.opp_image)%>">
</div>
  <div class="opportunity-card__info">
    <div class="d-flex justify-content-between">
      <h3>
        <%= opportunity.title %>
      </h3>
      <div>
      <span class="fw-bold"><%= opportunity.status ? "Status: Open" : "Status: Closed"%></span>
      </div>
    </div>
    <p>
      <%= icon('fa-solid', 'location-dot')%>  <%= opportunity.location ? opportunity.location : "" %>
    </p>

    <p class="flex-grow-1">
      <%= opportunity.description %>
    </p>

    <%= render partial: "shared/tags_container", locals: { tags: opportunity.tags } %>
  </div>
</div>

app/views/shared/_recent_opp.html.erb
<div class="d-flex flex-row recent-opp">
  <% Opportunity.last(3).each do |opportunity| %>
    <%= link_to opportunity_path(opportunity), class: "text-decoration-none" do %>
    <div class="opp-poster">
      <div class="color-bar"></div>
      <div class="p-3">
        <h4><%= opportunity.title %></h4>
        <p class="m-0">
          <%= icon('fa-regular', 'calendar')%>  <%= opportunity.date ? opportunity.date.strftime("%d %B, %Y") : "No Date Set" %>
        </p>
        <p class="m-0">
          <%= icon('fa-solid', 'location-dot')%>  <%= opportunity.location ? opportunity.location : "" %>
        </p>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_shortlisted_artist_card.html.erb
<div class="artist-card">
<div class="artist-card__image" style="background-image: url('<%= artist.artworks.empty? ? "" : artist.artworks.sample.image_url %>')"></div>
    <div class="artist-card__info">
      <h3>
        <%= "#{artist.first_name} #{artist.last_name}" %>
      </h3>
      <p>
        <%= icon('fa-solid', 'location-dot')%>  <%= artist.location ? artist.location : "" %>
      </p>
      <p>
        <%= icon('fa-solid', 'user')%>  <%= artist.pronouns ? artist.pronouns : "" %>
      </p>
      <p class="flex-grow-1">
        <%= artist.bio %>
      </p>

      <%= render partial: "shared/tags_container", locals: { tags: artist.tags } %>
    </div>
</div>

app/views/shared/_signup_modal.html.erb
  <button type="button" data-bs-toggle="modal" data-bs-target="#exampleModalz" class="nav-link sign-button">
    Sign Up
  </button>

  <div class="modal fade" id="exampleModalz" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Sign Up</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-footer">
          <%= link_to "I'm an artist", new_artist_registration_path, class: "btn btn-primary" %>
          <%= link_to "I'm looking for art", new_user_registration_path, class:"btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_tags_container.html.erb
<div class="tags-container">
  <% tags.each do |hashtag| %>
    <%= render partial: "shared/tag", locals: {tag: hashtag} %>
  <% end %>
</div>