config/routes.rb
Rails.application.routes.draw do
  devise_for :artists
  devise_for :users
  root to: "pages#home"
  resources :search, only: :index
  resources :shortlists
  resources :artists do
    resources :shortlisted_artists, only: :create
    resources :artworks, only: :destroy
  end
  resources :shortlisted_artists
  resources :users
  resources :artworks, except: :show
  resources :opportunities do
    resources :applications, only: %i[destroy toggle_success new create]
  end
  resources :applications, except: :edit do
    member do
      patch :toggle_success
    end
  end

  get "/my-opportunities", to: "opportunities#mine"
end

app/models/opportunity.rb
class Opportunity < ApplicationRecord
  belongs_to :user
  has_many :opportunity_tags, dependent: :destroy
  has_many :tags, through: :opportunity_tags
  has_many :applications, dependent: :destroy
  has_many :artists, through: :applications

  validate :validate_date

  has_one_attached :photo

  def validate_date
    if date.present? && date < Date.today
      errors.add(:date, "Invalid Date")
    end
  end
end

app/controllers/opportunities_controller.rb
class OpportunitiesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show index]
  skip_before_action :authenticate_artist!

  before_action :set_opportunities, only: %i[show edit update destroy]


  def index
    if params[:query].present?
      tagsquery = params[:query].split
      @opportunities = Opportunity.joins(:tags).where(tags: {name: tagsquery} ).uniq
    else
      @opportunities = Opportunity.all
    end
  end

  def mine
    @opportunities = Opportunity.where(user: current_user)
  end

  def show
    @applications = @opportunity.applications
    @application = Application.new

    if params[:tags]
      @new_tags = params[:tags].split(", ")
      @new_tags.each do |tag|
        tag_create = Tag.find_or_create_by(name: tag)
        if @opportunity.tags.include?(tag_create) == false
          OpportunityTag.create(tag: tag_create, opportunity: @opportunity)
        end
      end
    end

  end

  def new
    @opportunity = Opportunity.new
  end

  def create
    @opportunity = Opportunity.new(opportunity_params)
    @opportunity.user = current_user
    @opportunity.date = params[:opportunity][:date]
    if @opportunity.save
      redirect_to opportunity_path(@opportunity)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @opportunity.update(opportunity_params)
    redirect_to opportunity_path(@opportunity)
  end

  def destroy
    @opportunity = Opportunity.find(params[:id])
    @opportunity.destroy
    redirect_to my_opportunities_path


  end

  private

  def opportunity_params
    params.require(:opportunity).permit(:title, :location, :description, :status, :date, :opp_image)
  end

  def set_opportunities
    @opportunity = Opportunity.find(params[:id])
  end
end

app/views/opportunities/_form.html.erb
<%= simple_form_for(@opportunity) do |f| %>
<br>

<div class="d-flex w-50 justify-content-between">
  <strong><label for="status">Open/Close Opportunity</label></strong>
  <%= f.input :status, as: :boolean %>
</div>

  <%= f.input :title %>
  <%= f.input :location %>

  <%# date picker %>
  <%= f.input :date, as: :date, html5: true %>

  <%= f.input :description %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, "Save Details", class: "btn btn-primary w-100"%>
<% end %>

app/views/opportunities/edit.html.erb
<div class="custom-form">
  <h1>Editing <%= @opportunity.title %> </h1>
  <%= render 'form', opportunity: @opportunity %>
</div>

app/views/opportunities/index.html.erb
<%= month_calendar(attribute: :created_at, events: @opportunities) do |date, opps| %>
  <%= date.to_formatted_s(:short) %>

  <% opps.each do |opp| %>
    <%= link_to opportunity_path(opp), class: "text-decoration-none" do %>
    <span class="opportunity-calendar-event">
      <%= opp.title %>
    </span>
    <% end %>
  <% end %>
<% end %>

app/views/opportunities/mine.html.erb
<div class="shortlist-wrap">
  <div class="shortlist-yellow">
    <div class="shortlist-name">
      <h1>My opportunities</h1>
    </div>
  </div>

<div>
<%= link_to artists_path, class: "text-decoration-none" do %>
<div class="d-flex align-items-center mt-4">
<i class="fa-solid fa-circle-arrow-left fs-2"></i>
<% end %>
<p class="mb-0 ms-2">back</p>
</div>
</div>
  <div class="shortlist-artists">
    <%= link_to "Advertise a new opportunity", new_opportunity_path, class: "btn btn-primary advertise" %>
    <div class="shortlist-container">
      <% @opportunities.each do |opportunity| %>
        <%= link_to opportunity_path(opportunity), class: "text-decoration-none opportunity-card__link" do %>
          <%= render partial: "shared/opportunity_card", locals: {opportunity: opportunity} %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
















<%# <div class="container my-4 artist-card__container"> %>

    <%# <div class="d-flex justify-content-between align-items-center">
      <h1>My Opportunities</h1> %>
      <%# <%= link_to "Advertise a new opportunity", new_opportunity_path, class: "btn btn-primary" %>
    <%# </div> %>

    <%# <% @opportunities.each do |opportunity| %>
      <%# <%= link_to opportunity_path(opportunity), class: "text-decoration-none opportunity-card__link" do %>
        <%# <%= render partial: "shared/opportunity_card", locals: {opportunity: opportunity} %>
      <%# <% end %>
    <%# <% end %>

  <%# </div> %>

app/views/opportunities/new.html.erb
<div class="custom-form">
<h2>Create new opportunity</h2>
<%= render 'form', opportunity: @opportunity %>
</div>

app/views/opportunities/show.html.erb
<div class="opp-box d-flex">
  <div class="opp-headers w-75">
    <div class="back text-left w-100">
      <% if current_user == @opportunity.user %>
          <%= link_to my_opportunities_path, class: "text-decoration-none" do %>
            <div class="d-flex align-items-center">
              <i class="fa-solid fa-circle-arrow-left fs-2"></i>
          <% end %>
              <p class="mb-0 ms-2">back</p>
            </div>
      <% else %>
          <%= link_to :back, class: "text-decoration-none" do %>
            <div class="d-flex align-items-center">
              <i class="fa-solid fa-circle-arrow-left fs-2"></i>
          <% end %>
              <p class="mb-0 ms-2">back</p>
            </div>
      <% end %>
      <%# <div class="test-div">TESTER</div> %>
    </div>
    <div class="opportunity-info">
      <h1 class="mb-4"><%= @opportunity.title %></h1>

      <div class="opp-icons d-flex row text-left fs-5">
          <%# <%= @opportunity.location %>
          <div class="col-6 ic-1">
            <%= @opportunity.location ? @opportunity.location : "" %> <%= icon('fa-solid', 'location-dot')%>  <br>
            <%= @opportunity.date ? @opportunity.date.strftime("%d-%m-%Y") : "" %> <i class="fa-solid fa-calendar-days"></i>
          </div>
          <div class="col-6 ic-2">
            <i class="fa-regular fa-user"></i> <%= @opportunity.user.first_name %> <%= @opportunity.user.last_name %> <br>
            <i class="fa-regular fa-square-check"></i> <%= @opportunity.status ? "Open for Applications" : "This Opportunity is now Closed!" %>
          </div>
      </div>
      <br>
      <div class="tags-box my-2">
        <%= render partial: "shared/tags_container", locals: { tags: @opportunity.tags }, class: "current-tags" %>
        <% if current_user == @opportunity.user && @opportunity.status %>
          <form action='/opportunities/<%= @opportunity.id %>' data-controller="tom-select" class="opp-tags my-2">
            <div class="d-flex flex-row w-100">
            <input type="hidden" value="" name="tags" id="tag-box">
            <select data-tom-select-target="selector" data-action="input->tom-select#change" multiple name="newtag" id="select-tags" class="flex-grow-1">
              <% Tag.all.each do |tag| %>
                <option value='<%= tag.name %>'><%= tag.name %></option>
              <% end %>
            </select>
            <input type="submit" value="Add Tags" class="btn btn-primary btn-sm">
            </div>
          </form>
        <% end %>
      </div>
      <br>


      <div class="opp-desc">
        <%= @opportunity.description %>
      </div>
      <br>
    <div class="opp-applicants">
      <% if current_user == @opportunity.user && @opportunity.status%>
        <div class="apps-title my-1">
          <h3>These Artists Have Applied</h3>
        </div>
      <% elsif @opportunity.status == false %>
        <h3 class="border-bottom">Opportunity now closed</h3>
      <% end %>
      <div class="applications-box d-flex flex-column">
        <% if @opportunity.status == true %>
          <% if current_user == @opportunity.user %>
            <% @opportunity.applications.each do |application| %>
                <% artist = application.artist %>
                <% if application.success == true %>
                  <% next %>
                <% else %>
                  <div class="appl-card my-2">
                    <div class="m-1">
                      <%# Artist Avatar %>
                     <a id="applied-click" href='/artists/<%= artist.id %>' style="color:black;">
                        <% if artist.photo.key %>
                          <%= cl_image_tag artist.photo.key, crop: fill, class: "avatar" %>
                        <% else %>
                          <%= image_tag "https://news.artnet.com/app/news-upload/2022/05/SHGH2-e1652097979660-256x256.jpg", class: "avatar" %>
                        <% end %>
                        <br>
                        <strong><%= artist.first_name %> <%= artist.last_name %></strong>
                      </a>
                    </div>
                    <div class="text-center d-flex align-items-center">
                      <%= application.content %>
                    </div>
                    <div class="accept-deny">
                      <%= button_to "accept", toggle_success_application_path(application), method: :patch, class: "accept-b app-btn" %>
                      <% @application = Application.find(application.id) %>
                      <%= link_to 'reject', opportunity_application_path(@opportunity, application: application), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "reject-b app-btn" %>
                    </div>
                  </div>
                <% end %>
              <% end %>
            <% elsif current_artist %>
              <%# TODO Render the app form if not already applied %>
              <% if current_artist.applications.empty? %>

                  <%= render 'applications/form' %>
              <% else %>
                <% unless current_artist.applications.where(artist_id: current_artist.id, opportunity_id: @opportunity.id).empty? %>
                  <div class="applied">
                    <h2>You've applied!</h2>
                  </div>
                <%else %>
                  <div class="apply-here">
                    <h3>Apply Here</h3>
                  </div>
                  <%= render 'applications/form' %>
                <% end %>
              <% end %>
          <% end %>
          <% end %>
        </div>
    </div>
  </div>
    </div>

  <aside class="side-info">
    <div class="px-4 pt-5">
      <%# TODO: change below link path %>
        <%# HERE FOR WHEN IMAGES ARE ATTACHED %>


           <img class="opp-img" src="<%= image_path (@opportunity.opp_image)%>">

          <%# <img src="https://www.scotsman.com/webimg/b25lY21zOmFiMTA0ZTA1LTgzOWEtNDhiNy04N2FjLTZkNTVmNTJhNmU1MjoyZjZhNzRlYS0yNWIyLTQzNzItYmNiNi00NGE1MWI3MWFiNzE=.jpg?crop=61%3A45%2Csmart&width=800" class="opp-pic shadow-sm w-100"> %>

      <% if current_user == @opportunity.user && @opportunity.status %>
        <div class="button-box">
          <%= link_to 'Edit This Opportunity', edit_opportunity_path(@opportunity), class: "btn btn-secondary" %>
        <%= link_to opportunity_path(@opportunity),
            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
            class: "text-danger fw-bold text-decoration-none w-100 mt-2" do %>
          <%= icon('fa-regular', 'trash-can') %> Remove Opportunity
        <% end %>
        </div>

      <% end %>

    </div>
    <br>
    <div class="successful-art text-center">
      <% if current_user == @opportunity.user %>
        <h5 class="success-header">Accepted Artists</h5>
          <% @opportunity.applications.each do |application| %>
            <% if application.success == true %>
              <div class="appl-card-small my-1">
                <div>
                  <a href='/artists/<%= application.artist.id %>' style="text-decoration:none; color: black;">
                    <div>
                      <%= image_tag "https://news.artnet.com/app/news-upload/2022/05/SHGH2-e1652097979660-256x256.jpg", class: "avatar" %>
                    </div>
                    <%= application.artist.first_name %> <%= application.artist.last_name %>
                  </a>
                </div>
                <div class="align-items-center d-flex">
                  <strong class="text-success">Accepted</strong>
                </div>
              </div>
            <% end %>
          <% end %>
      <% end %>
    </div>
  </aside>
</div>